### ISSUE TITLE
Error while execute train data ns3_stable_solve.py

### ISSUE THREAD

**Issue by muham210892** [haidlir/ns3-drl-cc#2]
Hi Authors,

I tried to run ns3_stable_solve.py with error as follow

fatal error: ns3/opengym-module.h: No such file or directory
    5 | #include "ns3/opengym-module.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I searched opengym-module.h on ns-3 dev repository but can't found.
If you have any solution please kindly help me.

**Comment by haidlir** [comment]
Have you successfully installed the required python version and python packages listed in the requirements.txt file?

**Comment by fikri210892** [comment]
Hi Author, thank you for your reply.
I have installed packages on requirement.txt and opengym error has been solved.
if you don't mind, could you inform the sequence for running the simulation?
which first, second etc..
